[package]
name = "libphext"
version = "0.1.9"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A rust-native implementation of phext"
homepage = "https://phext.io/"
license = "MIT"
edition = "2021"

[dependencies]
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }