[package]
name = "libphext"
version = "0.1.0"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A rust-native implementation of phext"
homepage = "https://phext.io/"
license = "MIT"
edition = "2021"

[dependencies]